version: '3.3'

services:
    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017

    ttd:
        container_name: reviewzone_comments
        build: '.'
        ports:
            - 3000:3000
      
    